// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuw6dSLMwJOI1DVaF4i2bnJRXVd-7N6_8',
    appId: '1:955333261797:web:923e72f63824d9f84b570c',
    messagingSenderId: '955333261797',
    projectId: 'patroli-e48c9',
    authDomain: 'patroli-e48c9.firebaseapp.com',
    storageBucket: 'patroli-e48c9.firebasestorage.app',
    measurementId: 'G-KRHFLK6LF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuH5a4ESmPX2VE45JqMi5Ga9DPQjhqBNw',
    appId: '1:955333261797:android:1eda59be8befcd414b570c',
    messagingSenderId: '955333261797',
    projectId: 'patroli-e48c9',
    storageBucket: 'patroli-e48c9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuw6dSLMwJOI1DVaF4i2bnJRXVd-7N6_8',
    appId: '1:955333261797:web:d3aba094912b76084b570c',
    messagingSenderId: '955333261797',
    projectId: 'patroli-e48c9',
    authDomain: 'patroli-e48c9.firebaseapp.com',
    storageBucket: 'patroli-e48c9.firebasestorage.app',
    measurementId: 'G-E42H9YZYJF',
  );
}
